language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: 
  - printf '{"%s"{"JAVA_VERSION":"%s","BRANCH":"%s","JOB_ID":"%s"}}\n' "$COMMIT" "$(./scripts/java_version.sh)" "$BRANCH" "$JOB_ID"
script: ./gradlew clean build
after_success:
  - printenv
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
notifications:
  irc: "irc.esper.net#ChimeIn"