language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: 
  - chmod +x ./scripts/db_update.sh
  - ./scripts/db_update.sh
script: ./gradlew clean build
after_success:
  - printenv
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
notifications:
  irc: "irc.esper.net#ChimeIn"