language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: true
script: ./gradlew clean build
after_success:
  - printenv
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
notifications:
  irc: "irc.esper.net#ChimeIn"