language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: true
script: ./gradlew clean build
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
notifications:
  irc:
    channels:
      - "irc.esper.net#ChimeIn"
    on_success: change
    on_failure: always
    template:
      - "%{repository_name}#%{build_number} (%{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"