language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: 
  - curl -X PUT -d '$(./scripts/db_data.sh)' https://irc-bot-backend.firebaseio.com/builds.json?auth=cufRWsNn5Xos90zvdJE8qHMp2kCiXwZ6Xw5a2n6p
script: ./gradlew clean build
after_success:
  - printenv
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
notifications:
  irc: "irc.esper.net#ChimeIn"