language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: 
  - chmod +x ./scripts/db_update.sh
  - chmod +x ./scripts/db_update_failure.sh
script: ./gradlew clean build
after_success:
  - ./scripts/db_update.sh
after_failure:
  - ./scripts/db_update_failure.sh
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper