language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: 
  - ls -a $HOME
  - cat $HOME/.bashrc
  - cat $HOME/.bash_profile
  - curl
script: ./gradlew clean build
after_success:
  - printenv
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
notifications:
  irc: "irc.esper.net#ChimeIn"